name: 'Cloud DEMO Deploy'

on:
  repository_dispatch:
    types: [dispatch_demo_deploy]
  workflow_dispatch:
    inputs:
        run_id:
          description: 'Run ID. Specify unique workflow run id'
          required: true
          default: ''
        jiraId:
          description: 'Jira Ticket ID'
          required: true
          default: ''

jobs:
  log-inputs:
    name: Log inputs
    runs-on: [self-hosted, ubuntu-latest, ondemand]
    steps:
    - name: Display inputs
      run: |
        echo '${{ toJson(github.event.inputs) }}'
        echo '${{ toJson(github.event.client_payload) }}'
  deploy:
    name: Cloud Deploy
    runs-on: [self-hosted, ubuntu-latest, ondemand]
    steps:
    - name: Repository Dispatch
      uses: chillianosson/action-practice/.github/workflows/e2e-quality-gate.yml
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: demo_deploy_trigger_tests
        # client-payload: '{"ref_name": "${{ env.CI_META_BRANCH }}", "sha": "${{ env.CI_META_SHA }}", "jiraId": "${{ env.CI_JIRA_ID }}", "demo_url": "${{ env.CI_DEMO_URL }}", "demo_deploy_seconds": "300"}'
